# .github/workflows/test-connection.yml
name: Test SSH Connection

on:
  workflow_dispatch:  # Only run manually

jobs:
  test-connection:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test SSH Connection
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          echo "=== SSH Connection Successful! ==="
          echo "Connected to: $(hostname)"
          echo "User: $(whoami)"
          echo "Current directory: $(pwd)"
          echo "OS Info: $(cat /etc/os-release | grep PRETTY_NAME)"
          echo "Docker installed: $(which docker || echo 'Docker not found')"
          echo "Docker Compose installed: $(which docker-compose || echo 'Docker Compose not found')"
          echo "Can run Docker: $(sudo docker --version || echo 'Cannot run Docker')"
          echo "=== Test Complete ==="